### ISSUE TITLE
可以尝试linux shell发微信

### ISSUE THREAD

**Issue by ghost** [ipreacher/Stock_WeChat#4]
你好，我看你说微信关闭第三方API，我之前试过linux 发微信，大概就是事件触发执行sh脚本实现发微信，你可以参考下

https://ntgeralt.blogspot.com/2018/10/arduino-rm04-wifi.html
https://ntgeralt.blogspot.com/2017/08/linux-ping.html
https://ntgeralt.blogspot.com/2018/10/vps-linux.html

**Comment by onshek** [comment]
谢谢。这已经脱离了本项目原本的愿景。其实换成telegram方便很多。
